### ISSUE TITLE
Create Readme

### ISSUE THREAD

**Issue by andy-schwedler** [andy-schwedler/capstone-project#15]
## Value Proposition

**As a** user

**I need** recognise the purpose of this app

**to be able to** better understand if it has the features I am looking for.

## Description

Scribble / design or text

## Acceptance Criteria

- Know what this App is about

## Tasks

(for developers team)

- [ ] describe tech stack
- [ ] answer marketing questions (i.e. what inspired you to start this project)

EXAMPLES: 
https://github.com/mar-zim/capstone-project
https://github.com/miriamhaenle/capstone-project
https://github.com/ttaannjjaa/capstone-project
https://github.com/marcbendixen/capstone-project
https://github.com/MelGGit/capstone-project
https://github.com/sebuzz/nf-capstone
https://github.com/JpunktWpunkt/nf-capstone
https://github.com/frederikebruendermann/capstone-project
https://github.com/LisanneArdern/capstone-project

**Comment by Elgin-Schultz** [comment]
Very helpful! I really appreciate if a Readme gives me good information about the project!
